/**
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package ua.iot.lviv.client.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModelProperty;


/**
 * SoundBoard
 */
@javax.annotation.Generated(value = "class io.swagger.codegen.languages.JavaClientCodegen", date = "2019-10-27T21:41:25.115+02:00")
public class SoundBoard   {
  @SerializedName("backgroundPhoto")
  private byte[] backgroundPhoto = null;

  @SerializedName("description")
  private String description = null;

  @SerializedName("duration")
  private String duration = null;

  @SerializedName("fileData")
  private byte[] fileData = null;

  @SerializedName("foregroundPhoto")
  private byte[] foregroundPhoto = null;

  @SerializedName("id")
  private Integer id = null;

  @SerializedName("movieName")
  private String movieName = null;

  public SoundBoard backgroundPhoto(byte[] backgroundPhoto) {
    this.backgroundPhoto = backgroundPhoto;
    return this;
  }

   /**
   * Get backgroundPhoto
   * @return backgroundPhoto
  **/
  @ApiModelProperty(example = "null", value = "")
  public byte[] getBackgroundPhoto() {
    return backgroundPhoto;
  }

  public void setBackgroundPhoto(byte[] backgroundPhoto) {
    this.backgroundPhoto = backgroundPhoto;
  }

  public SoundBoard description(String description) {
    this.description = description;
    return this;
  }

   /**
   * Get description
   * @return description
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getDescription() {
    return description;
  }

  public void setDescription(String description) {
    this.description = description;
  }

  public SoundBoard duration(String duration) {
    this.duration = duration;
    return this;
  }

   /**
   * Get duration
   * @return duration
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getDuration() {
    return duration;
  }

  public void setDuration(String duration) {
    this.duration = duration;
  }

  public SoundBoard fileData(byte[] fileData) {
    this.fileData = fileData;
    return this;
  }

   /**
   * Get fileData
   * @return fileData
  **/
  @ApiModelProperty(example = "null", value = "")
  public byte[] getFileData() {
    return fileData;
  }

  public void setFileData(byte[] fileData) {
    this.fileData = fileData;
  }

  public SoundBoard foregroundPhoto(byte[] foregroundPhoto) {
    this.foregroundPhoto = foregroundPhoto;
    return this;
  }

   /**
   * Get foregroundPhoto
   * @return foregroundPhoto
  **/
  @ApiModelProperty(example = "null", value = "")
  public byte[] getForegroundPhoto() {
    return foregroundPhoto;
  }

  public void setForegroundPhoto(byte[] foregroundPhoto) {
    this.foregroundPhoto = foregroundPhoto;
  }

  public SoundBoard id(Integer id) {
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @ApiModelProperty(example = "null", value = "")
  public Integer getId() {
    return id;
  }

  public void setId(Integer id) {
    this.id = id;
  }

  public SoundBoard movieName(String movieName) {
    this.movieName = movieName;
    return this;
  }

   /**
   * Get movieName
   * @return movieName
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getMovieName() {
    return movieName;
  }

  public void setMovieName(String movieName) {
    this.movieName = movieName;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SoundBoard soundBoard = (SoundBoard) o;
    return Objects.equals(this.backgroundPhoto, soundBoard.backgroundPhoto) &&
        Objects.equals(this.description, soundBoard.description) &&
        Objects.equals(this.duration, soundBoard.duration) &&
        Objects.equals(this.fileData, soundBoard.fileData) &&
        Objects.equals(this.foregroundPhoto, soundBoard.foregroundPhoto) &&
        Objects.equals(this.id, soundBoard.id) &&
        Objects.equals(this.movieName, soundBoard.movieName);
  }

  @Override
  public int hashCode() {
    return Objects.hash(backgroundPhoto, description, duration, fileData, foregroundPhoto, id, movieName);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SoundBoard {\n");
    
    sb.append("    backgroundPhoto: ").append(toIndentedString(backgroundPhoto)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    duration: ").append(toIndentedString(duration)).append("\n");
    sb.append("    fileData: ").append(toIndentedString(fileData)).append("\n");
    sb.append("    foregroundPhoto: ").append(toIndentedString(foregroundPhoto)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    movieName: ").append(toIndentedString(movieName)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


}

